@startuml
start
:将插入节点[x]设置成红色;
while(x节点为非root 且 其父节点为红色 ) is (y)
 if( 当x的父节点是x的祖父节点的左孩子时 ) then(y)
    :获取x的右叔节点;
    if(x的叔节点是红色) then (y)
    :设置父节点为黑色;
    :设置叔节点为黑色;
    :设置祖父节点为红色;
    :x 设置成x的祖父节点;
    else (n)
        if(x 是右孩子节点) then(y)
            :x设置成x的父节点;
            :左旋x的父节点;
        endif
        :设置x的父节点为黑色;
        :设置x的祖父节点为红色;
        :右旋x的祖父节点;
    endif
 else (n)
    :获取x的左叔节点;
    if(x的叔节点为红色) then(y)
        :设置x的父节点为黑色;
        :设置x的叔节点为黑色;
        :设置x的祖父节点为红色;
        :x 设置成x的祖父节点;
    else(n)
        if(x 是左孩子节点) then(y)
        :x设置成x的父节点;
        :右旋x的父节点;
        endif
        :设置x的父节点黑色;
        :设置x的祖父节点为红色;
        :左旋x的祖父节点;
    endif
 endif
endwhile (n)
:将root节点设置成黑色;
stop
@enduml